# Prometheus configuration
# Monitoring Lab: Prometheus + Grafana + Node Exporter

global:
  # Интервал сбора метрик
  scrape_interval: 15s

  # Интервал проверки Alert Rules
  evaluation_interval: 15s


# Файлы с правилами алертов
# В данном проекте Alert Rules настроены через Grafana
rule_files:
  # - "alerts.yml"


# Источники метрик
scrape_configs:

  # VM1 Linux server
  # Node Exporter предоставляет системные метрики
  - job_name: "vm1"

    scrape_interval: 15s

    static_configs:
      - targets:
          - "192.168.56.101:9100"


  # Локальный Node Exporter (если используется)
  - job_name: "node"

    static_configs:
      - targets:
          - "localhost:9100"